### ISSUE TITLE
bitwise and between UInt8 and Int8

### ISSUE THREAD

**Issue by alist** [Spark-Innovations/SC4#1]
`u8a_cmp(my_pk, a2: rx_pk)` returns ±1 (Int8), proceeds bitwise AND with 3 (Int8), then performs bitwise and with `lhs` `(nonce[0] & 0xFC)` (UInt8).  

Implicit conversion between UInt8 and Int8. Conversion should be explicit.

https://github.com/Spark-Innovations/SC4/blob/47c1624/sc4-py/sc4.py#L361

**Comment by rongarret** [comment]
I don't think this is a valid issue.  Python doesn't distinguish between Int and UInt.  All integers in Python are signed.

**Comment by alist** [comment]
sounds right! How about in https://stage.sc4.us/sc4/sc4.js ?

**Comment by rongarret** [comment]
Same story: JS doesn't even have real integers, only (signed, obviously) floats.  But even in C, which (again obviously) has both signed and unsigned ints I don't think this matters.  Signedness only matters when you're doing arithmetic operations, not logical operations.

**Comment by alist** [comment]
Ha, right, of course. Thanks Ron

**Comment by rongarret** [comment]
Sure thing.  Thanks for looking at the code!
